pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/resouce?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  redis:
    host: localhost
    port: 6379
    password:
    database: 2

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #对应mapper的实体类
  type-aliases-package: com.resource.common.entity
  check-config-location: true
  global-config:
    db-config:
      id-type: auto
      capital-mode: true
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cors-param:
  corsDomainName: "*"

##日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    path: ../logs/resource-admin-api

# jwt配置
jwt:
  # 过期时间, 单位分
  expirationDate: 60
  # token 的 http header key值
  headerName: lsh-admin-token
  key: 2Ke6TiOmGSWR9FiU2Ke6TiOmGSWR9FiU2Ke6TiOmGSWR9FiU
  # 最小刷新时间, 单位分
  minRefreshDate: 30

# 系统配置参数
sys-config:
  # rsa 私钥
  private-key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIo6Ckhtfm2F4JAB0PpCb24l7NaQRz/9sGpfAGDVp/CdYw4vssrbzkI6kuyfsQaVzrLlKr6RTjRazEqu5u/X5Ps+VduzTnwyuKAftUsW0Ol/UolDQRwYJ6P2aNLmvUY4H3XLBx7tYesbDekV8SW+D+xXRcrl1y4REzHt7CsS063RAgMBAAECgYBlq0Mc+sxfKnV99pgLOwpS7jpBp2WAv8wesTnJ/9zCskDFknfjlcEkHYkr2lmPCmk6VC0YdjAbeh2BYRwjlZypyO8oo3VNI28QNmvKCfWdf6XUYt1CArAJUFjd1panrgJxXGrGIDPh4H65/eH363QA/XXCnetcJmOBAIQHpbJxsQJBANRl5zpH9eGT8W6JEde8d/K9d6XCCLCsQjLJEneabKrTCkpNnf7dBN/klYLE0hU1zTPtOt5nLXK1mQWB5iyIRtcCQQCmmjsc/YOzPhy5I43TsrUIF8xhZB0c0rDZmViO+hKFtBbgZxEtbi3yFQaxbGhSTunfvGeQD/ObzAsL8wKBgaOXAkASmKF4HtjOWU+oJ+QiCWRPInuZTbXJEivxml09j424HyYlf0o4CE3m9HKKsoTaSo2e4ERpOItoIbI2Iztt5ridAkAk2l8TJZ0ZbDbsWUoJNzHGbYU/UecCtjR6neoyDm1EeDbLQuFQ3Ft7fl0xqBpXgq9HV6TNAEpR/0u+Q+4c+bFXAkBzjLLVeOObxot34LqRhaZPGmQVvPxII90t2/xVsDamRS1ipybjP2c5Wq4axRdLtTMdNsTQyMO6CvkYCdr/92kf
  # rsa 公钥
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCKOgpIbX5theCQAdD6Qm9uJezWkEc//bBqXwBg1afwnWMOL7LK285COpLsn7EGlc6y5Sq+kU40WsxKrubv1+T7PlXbs058MrigH7VLFtDpf1KJQ0EcGCej9mjS5r1GOB91ywce7WHrGw3pFfElvg/sV0XK5dcuERMx7ewrEtOt0QIDAQAB
